nsconfig: use $(command) rather than backticks
Reference: http://mywiki.wooledge.org/BashFAQ/082
Signed-off-by: Sami Kerola <kerolasa@iki.fi>

diff --git a/bin/nsconfig b/bin/nsconfig
--- a/bin/nsconfig
+++ b/bin/nsconfig
@@ -4,7 +4,7 @@
 
 set -e
 
-M4=`which gm4` || M4=`which m4` || ( echo "Unable to find M4!" ; exit 1 )
+M4=$(which gm4) || M4=$(which m4) || ( echo "Unable to find M4!" ; exit 1 )
 DOMAINS=cf/domains
 
 if [ ! -f $DOMAINS ] ; then
